#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Roman Peshkov <peshkovroman@gmail.com>
#

# Prezto initialization
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# ZPlug
export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

#
# NVM
#
export NVM_DIR="$HOME/.nvm"
# Only do lazy loading when NOT inside vscode
# https://github.com/Microsoft/vscode/issues/18556#issuecomment-299636934
if [ -z "$VSCODE_PID" ]; then
    export NVM_LAZY_LOAD=true;
fi
zplug "lukechilds/zsh-nvm"

zplug load

export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

export PAGER="less"
export LESS="-R -X -F"

# Customize to your needs...
fpath=(~/.zsh/completion $fpath) 
autoload -U compinit
compinit

#
# Aliases
#
#alias ls='ls -F'
#alias ll='ls -alF'
#alias la='ls -A'
#alias l='ls -CF'
alias ls='exa -F  --header'
alias ll='exa -lF --time-style=long-iso --header'

# Measure directories in current path
alias duh='du -chd1'

# I prefer nvim
alias vim='nvim'
alias fm='vifm'

# Open current folder in VS Code
alias coder='code -r .'
alias notes='vim -c "cd ~/Dropbox/Notes/" ~/Dropbox/Notes/'

# Fast http serve for current folder
alias serve='python -m SimpleHTTPServer'

alias wifi='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport'

hash -d -- dev=$HOME/Developer
hash -d -- dropbox=$HOME/Dropbox
hash -d -- notes=$HOME/Dropbox/Notes
hash -d -- downloads=$HOME/Downloads

# Open github page for current repo+branch+path in browser
# Taken from https://github.com/jonhoo/configs/blob/master/.bashrc
alias github="((git config --local --get remote.origin.url | sed -e 's/^.*git@github.com:/https:\/\/github.com\//g' -e 's/\.git$/\/tree\//g'); (git branch 2>/dev/null| sed -n '/^\*/s/^\* //p'); echo '/'; (git rev-parse --show-prefix)) | tr -d '\n' | xargs $BROWSER"

#
# FZF
#
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

#export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*" 2> /dev/null'
#export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

export FZF_DEFAULT_COMMAND="fd . $HOME"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd -t d . $HOME"

#
# Rust
#
if [ -x "$(command -v rustc)" ]; then
    export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
fi

