# Locale

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

if [[ "$OSTYPE" == darwin* ]]; then
    export BROWSER="open"
fi

export EDITOR="nvim"
export VISUAL="nvim"
export PAGER="less"

export GOPATH="$HOME"
export PATH="$GOPATH/bin:$PATH"

export SNV="v8.11.3"
export PURE_PROMPT_SYMBOL="λ"

export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
export LS_COLORS="di=1;34:ln=1;35:so=1;31:pi=1;33:ex=1;32:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"

