#
# Modules
#
autoload -U colors && colors
autoload -U edit-command-line
autoload -U select-word-style && select-word-style bash

#
# Options
#
setopt auto_pushd
setopt pushd_ignore_dups
setopt auto_remove_slash
setopt no_beep
setopt extended_glob

#
# Bindings
#
bindkey -e

# delete char with backspaces and delete
bindkey '^[[3~' delete-char
bindkey '^?' backward-delete-char
bindkey '\e[1~' beginning-of-line
bindkey '\e[4~' end-of-line
bindkey '^[[Z' reverse-menu-complete
bindkey '\e\e[C' forward-word
bindkey '\e\e[D' backward-word

function _fzf-tmux-pane-path {
    zle -U "$(tmux lsp -F \#{pane_current_path} | uniq | fzf --height=7)"
    zle redisplay
}
zle -N _fzf-tmux-pane-path
bindkey '\et' _fzf-tmux-pane-path

function copy-kill-whole-line {
    zle kill-whole-line
    echo -n $CUTBUFFER | pbcopy
}
zle -N copy-kill-whole-line
bindkey '^x^x' copy-kill-whole-line

zle -N edit-command-line
bindkey '^x^e' edit-command-line

#
# Completion
#
fpath=(~/.zsh/completion $fpath)
autoload -Uz compinit && compinit -i

# forces zsh to realize new commands
zstyle ':completion:*' completer _oldlist _expand _complete _match _ignored _approximate

# matches case insensitive for lowercase
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# pasting with tabs doesn't perform completion
zstyle ':completion:*' insert-tab pending

# rehash if command not found (possibly recently installed)
zstyle ':completion:*' rehash true

# menu if nb items > 2
zstyle ':completion:*' menu select=2

# colored menu
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

#
# Aliases
#

# Directory stack navigation
alias d="dirs -v"
for index ({1..9}) alias "$index"="cd +${index}"; unset index

alias ls='ls -F'
alias l='ls -l'
alias lla='ls -la'
alias vim='nvim'
alias duh='du -chd1'
alias serve='http-server'
alias coder='code -r .'
alias dev='cd ~dev'
alias cwd='pwd | pbcopy'
alias weather='curl wttr.in'

alias dots='cd $HOME/.dotfiles/'

alias k='kubectl'
compdef k='kubectl'

hash -d -- dev=$HOME/Developer
hash -d -- n=$HOME/Documents/Notes

export FZF_DEFAULT_COMMAND="fd . $HOME"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd -t d . $HOME"

source "${HOME}/.zgen/zgen.zsh"
if ! zgen saved; then
    zgen load mafredri/zsh-async
    zgen load sindresorhus/pure
    zgen load eendroroy/zed-zsh
    zgen load zsh-users/zsh-syntax-highlighting
    zgen save
fi

#
# History
#
HISTFILE=~/.zsh_history
HISTSIZE=1024
SAVEHIST=1024
setopt append_history
setopt hist_ignore_all_dups
setopt hist_reduce_blanks
setopt hist_verify
setopt inc_append_history
setopt share_history
setopt bang_hist

[ -f "$HOME/.zshrc_local" ] && source "$HOME/.zshrc_local"
